### ISSUE TITLE
Game crashed when loading maps.

### ISSUE THREAD

**Issue by Lehmaning** [pserwylo/beat-game#54]
Here is the crash log:

android version=5.1(22)
hardware=mt6755d
version name=0.1.0
supported ABIs=arm64-v8a & armeabi-v7a & armeabi

java.lang.OutOfMemoryError: Failed to allocate a 37739532 byte allocation with 1578944 free bytes and 1541KB until OOM
	at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
	at com.serwylo.beatgame.audio.fft.FFTKt.readPcm(FFT.kt:193)
	at com.serwylo.beatgame.audio.fft.FFTKt.calculateMp3FFT(FFT.kt:20)
	at com.serwylo.beatgame.audio.AudioIOKt.loadFromDisk(AudioIO.kt:41)
	at com.serwylo.beatgame.audio.AudioIOKt.loadWorldFromMp3(AudioIO.kt:26)
	at com.serwylo.beatgame.screens.LoadingScreen$startLoading$1.run(LoadingScreen.kt:32)
	at java.lang.Thread.run(Thread.java:818)

**Comment by pserwylo** [comment]
Thanks for the report @Lehmaning. I tried to google the device mt6755d to find out how much memory it had, but was not successful. Do you know how much ram your device has?

Nevertheless, v0.1.0 uses a pretty crude method of processing sound files. v0.2.0 will be built by F-Droid soon, and this uses less memory when processing levels. However, on large files it will certainly still crash. The whole process can be streamlined so that it doesn't buffer the entire song and perform FFT's of the entire song, but rather just a few seconds at a time. Just this will be a bit of an undertaking so not at the top of my list. Let's wait and see if v0.2.0 is able to solve it at least for some of your MP3 files.

**Comment by Lehmaning** [comment]
> Thanks for the report @Lehmaning. I tried to google the device mt6755d to find out how much memory it had, but was not successful. Do you know how much ram your device has?

**Comment by Lehmaning** [comment]
@pserwylo My device has 4GB RAM. 
After I reinstall the game, it crashes no longer, but the picture seems a little laggy. 
Hope the future version will be optimized.

**Comment by Lehmaning** [comment]
v0.2.0 looks smoother, and the problem have been got solved, pretty cool.
